# STAGE 1

FROM node:18.13.0-alpine3.17 as build
WORKDIR /app
COPY . /app/
RUN npm i
RUN npm run build

# STAGE 2

FROM nginx:1.23.3-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]