# STAGE 1

FROM node:18.13.0-alpine3.17 as build

WORKDIR /backend

COPY package*.json ./
COPY tsconfig.json ./
COPY src ./src
RUN npm i 
RUN npm run build 


FROM node:18.13.0-alpine3.17
WORKDIR /backend
ENV PORT=80
COPY --from=build /backend/package*.json ./
RUN npm ci --only=production
COPY --from=build /backend/dist .

EXPOSE 80

CMD ["node","index.js"]